website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    is_admin = False

    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        if email == 'admin' and password == 'admin':
            flash('Logged in as admin!', category='success')
            return redirect(url_for('views.admin_users'))

        user = User.query.filter_by(email=email).first()

        if user and check_password_hash(user.password, password):
            if user.is_active:
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Votre compte est désactivé. Veuillez contacter l\'administrateur.', category='error')
                return redirect(url_for('auth.login'))

        flash('Incorrect email or password. Please try again.', category='error')

    return render_template("login.html", user=current_user, is_admin=is_admin)

@auth.route('/forgot', methods=['GET', 'POST'])
def forgot():
    if request.method == 'POST':
        email = request.form.get('email')
        new_password = request.form.get('new_password')
        confirm_password = request.form.get('confirm_password')

        # Recherchez l'utilisateur dans la base de données par e-mail
        user = User.query.filter_by(email=email).first()

        # Vérifiez que le nouveau mot de passe et la confirmation correspondent
        if new_password != confirm_password:
            flash('Les mots de passe ne correspondent pas. Veuillez réessayer.', category='error')
        else:
            if user:
                # Mettez à jour le mot de passe de l'utilisateur existant
                user.password = generate_password_hash(new_password)
                db.session.commit()
                flash('Mot de passe mis à jour avec succès.', category='success')
                return redirect(url_for('views.home'))
            else:
                # Si l'utilisateur n'existe pas, informez l'utilisateur
                flash('Aucun utilisateur associé à cet e-mail. Veuillez vous inscrire.', category='error')

    return render_template("forgot.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

website/views.py
import codecs
import csv
from datetime import datetime
from sqlite3 import IntegrityError
from io import TextIOWrapper
from datetime import datetime
import requests
from flask import Blueprint, render_template, request, flash, jsonify, url_for, redirect, Response
from flask_login import login_required, current_user
from .models import Note, User, Contact
from . import db
import json
from flask import jsonify
from sqlalchemy import or_, asc

views = Blueprint('views', __name__)


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')
        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)


@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})


@views.route('/')
def admin():
    is_admin = True
    users = User.query.all()

    return render_template("index.html", user=current_user)

@views.route('/users', methods=['GET', 'POST'])
def admin_users():
    is_admin = True

    if request.method == 'POST':
        # Récupérez l'ID de l'utilisateur à supprimer à partir du formulaire
        user_id = request.form.get('id')

        # Vérifiez si l'ID est valide et effectuez l'opération de suppression
        if user_id:
            user = User.query.get(user_id)
            if user:
                db.session.delete(user)
                db.session.commit()

    # Récupérez la liste mise à jour des utilisateurs après la suppression
    users = User.query.all()

    return render_template("admin_users.html", users=users, is_admin=is_admin, user=current_user)

@views.route('/admin')
def admin_home():
    is_admin = True
    users = User.query.all()

    return render_template("admin.html", user=current_user, is_admin=is_admin)


from flask import redirect, url_for


@views.route('/delete_user/<int:id>', methods=['POST'])
def delete_user(id):
    user = User.query.get(id)

    if user:
        db.session.delete(user)
        db.session.commit()

    # Redirigez l'administrateur vers la page des utilisateurs après la suppression
    return redirect(url_for('views.admin_users'))


from sqlalchemy import desc



@views.route('/contacts', methods=['GET'])
@login_required
def contacts():
    contacts_query = Contact.query.filter_by(user_id=current_user.id)
    contacts_query = contacts_query.order_by(asc(Contact.created_at))

    contacts = contacts_query.all()

    return render_template("contacts.html", user=current_user, contacts=contacts)



@views.route('/contacts/sort', methods=['GET'])
@login_required
def sort_contacts():
    # Get the sorting criterion and order from the request parameters
    sort_by = request.args.get('sort_by', 'created_at_asc')

    # Set the default sorting to 'created_at' in ascending order
    sort_column, sort_order = 'created_at', 'asc'

    # Determine the actual sorting criterion and order based on the user's selection
    if sort_by == 'first_name':
        sort_column, sort_order = 'first_name', 'asc'  # Default to ascending order for names

    elif sort_by == 'last_name':
        sort_column, sort_order = 'last_name', 'asc'  # Default to ascending order for names

    elif sort_by == 'email':
        sort_column, sort_order = 'email', 'asc'  # Default to ascending order for email

    elif sort_by == 'created_at_asc':
        sort_column, sort_order = 'created_at', 'asc'
    elif sort_by == 'created_at_desc':
        sort_column, sort_order = 'created_at', 'desc'

    # Query the contacts based on the user's ID and apply sorting
    contacts = (
        Contact.query
        .filter_by(user_id=current_user.id)
        .order_by(asc(sort_column) if sort_order == 'asc' else desc(sort_column))
        .all()
    )

    return render_template("contacts.html", user=current_user, contacts=contacts)


from sqlalchemy.exc import IntegrityError

@views.route('/add-contact', methods=['GET', 'POST'])
@login_required
def add_contact():
    if request.method == 'POST':
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        address = request.form.get('address')
        postal_code = request.form.get('postal_code')
        birthday = request.form.get('birthday')
        email = request.form.get('email')
        phone = request.form.get('phone')
        category = request.form.get('category')

        birthday = datetime.strptime(birthday, '%Y-%m-%d').date() if birthday else None
        existing_contact = Contact.query.filter_by(email=email, user_id=current_user.id).first()

        if existing_contact:
            flash('Un contact avec la même adresse e-mail existe déjà!', category='error')
        else:
            new_contact = Contact(
                first_name=first_name,
                last_name=last_name,
                address=address,
                postal_code=postal_code,
                birthday=birthday,
                email=email,
                phone=phone,
                category=category,
                created_at=datetime.utcnow(),
                updated_at=datetime.utcnow(),
                user_id=current_user.id
            )

            db.session.add(new_contact)

            try:
                db.session.commit()
                flash('Contact ajouté!', category='success')
            except IntegrityError as e:
                db.session.rollback()
                flash('Erreur lors de l\'ajout du contact. Veuillez réessayer.', category='error')
                print(f"IntegrityError: {str(e)}")

    return render_template("add_contact.html", user=current_user)


ALLOWED_EXTENSIONS = {'csv'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@views.route('/export-contacts-csv', methods=['GET'])
@login_required
def export_contacts_csv():
    contacts = Contact.query.filter_by(user_id=current_user.id).all()
    csv_data = [['Nom', 'Prenom', 'Adresse', 'Code postal', 'Date d\'anniversaire', 'Email', 'Numero de telephone', 'Categorie']]

    for contact in contacts:
        cleaned_address = clean_address(contact.address)
        csv_data.append([
            contact.first_name,
            contact.last_name,
            cleaned_address,
            contact.postal_code,
            contact.birthday,
            contact.email,
            contact.phone,
            contact.category
        ])

    csv_content = '\n'.join([','.join(map(str, row)) for row in csv_data])
    csv_content = codecs.encode(csv_content, 'utf-8')

    response = Response(csv_content, content_type='text/csv; charset=utf-8')
    response.headers['Content-Disposition'] = 'attachment; filename=all_contacts.csv'

    return response

def clean_address(address):
    # Ajoute ici toute logique de nettoyage nécessaire pour les adresses
    # Par exemple, suppression de caractères spéciaux indésirables, formatage, etc.
    cleaned_address = address.replace(',', ' ')  # Remplacer les virgules par un espace
    return cleaned_address


ALLOWED_EXTENSIONS = {'csv'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@views.route('/import-csv', methods=['POST'])
@login_required
def import_csv():
    if 'file' not in request.files:
        flash('Aucun fichier sélectionné.', category='error')
        return redirect(url_for('views.contacts'))

    file = request.files['file']

    if file.filename == '':
        flash('Aucun fichier sélectionné.', category='error')
        return redirect(url_for('views.contacts'))

    if file:
        try:
            csv_reader = csv.reader(TextIOWrapper(file, encoding='utf-8'), delimiter=',', quotechar='"')
            next(csv_reader)

            for row in csv_reader:
                first_name = row[0]
                last_name = row[1]
                address = row[2]
                postal_code = row[3]
                birthday = row[4]
                email = row[5]
                phone = row[6]
                category = row[7]

                existing_contact = Contact.query.filter_by(email=email).first()

                if not existing_contact:
                    new_contact = Contact(
                        first_name=first_name,
                        last_name=last_name,
                        address=address,
                        postal_code=postal_code,
                        birthday=birthday,
                        email=email,
                        phone=phone,
                        category=category,
                        created_at=datetime.utcnow(),
                        updated_at=datetime.utcnow(),
                        user_id=current_user.id
                    )

                    db.session.add(new_contact)

            db.session.commit()

            flash('Importation réussie.', category='success')
        except csv.Error as e:
            flash(f'Erreur lors de l\'importation du fichier CSV: {e}', category='error')

    return redirect(url_for('views.contacts'))

@views.route('/toggle_user/<int:id>', methods=['POST'])
def toggle_user(id):
    # Récupérer l'utilisateur de la base de données en utilisant l'id
    user = User.query.get(id)

    # Inverser l'état d'activation/désactivation
    user.is_active = not user.is_active

    # Sauvegarder les modifications dans la base de données
    db.session.commit()

    # Ajouter un message flash en fonction de l'état actuel de l'utilisateur

website/templates/add_contact.html
{% extends "base.html" %}
{% block title %}Ajouter un contact{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Balises meta, title, etc. -->

    <!-- Ajouter le lien vers le fichier CSS du Bootstrap Datepicker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

    <!-- Ajouter les liens vers les fichiers JS de Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- Add this to the head section of your HTML -->
<script src="https://cdn.jsdelivr.net/npm/places.js@1.17.1/dist/cdn/places.js"></script>


</head>
<body>
    <div class="text-center">
        <h1 style="margin-top: 40px;" class="mb-4">Ajouter un contact</h1>
    </div>
     <form method="post" action="{{ url_for('views.add_contact') }}" class="mx-auto col-md-6 mb-5">
        <div class="form-group">
            <label for="first_name">Prénom:</label>
            <input type="text" class="form-control" name="first_name" required>
        </div>

        <div class="form-group">
            <label for="last_name">Nom:</label>
            <input type="text" class="form-control" name="last_name" required>
        </div>



        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" name="email" required>
        </div>

       <!-- Update your address input field -->
<!-- Update your address input field -->
<div class="form-group">
    <label for="address">Adresse:</label>
    <input type="text" class="form-control" name="address" id="addressInput">
    <ul id="autocompleteResults"></ul>
</div>






        <div class="form-group">
            <label for="postal_code">Code postal:</label>
            <input type="text" class="form-control" name="postal_code">
        </div>




       <div class="form-group" >
    <label for="birthday">Date d'anniversaire:</label>
    <input type="date" class="form-control" name="birthday">
    <div class="input-group-addon"></div>
</div>




        <div class="form-group">
            <label for="phone">Numéro de téléphone:</label>
            <input type="text" class="form-control" name="phone" required>
        </div>

        <div class="form-group">
    <label for="category">Catégorie:</label>
    <select class="form-control " name="category">
        <option value="Travail">Travail</option>
        <option value="Ami">Ami</option>
        <option value="Famille">Famille</option>
    </select>
</div>


       <div class="text-center">
            <button type="submit" class="btn btn-primary">Ajouter le contact</button>
            <a href="{{ url_for('views.contacts') }}" class="btn btn-secondary">Retour</a>
        </div>
    </form>
<script>
document.addEventListener("DOMContentLoaded", function() {
    // Récupérer la référence de l'élément input et de la liste des résultats
    var addressInput = document.getElementById('addressInput');
    var autocompleteResults = document.getElementById('autocompleteResults');

    // Écouter l'événement d'entrée utilisateur pour déclencher la recherche d'autocomplétion
    addressInput.addEventListener('input', function() {
        // Récupérer la valeur de l'adresse entrée par l'utilisateur
        var query = addressInput.value.trim();

        // Effacer la liste des résultats précédents
        autocompleteResults.innerHTML = '';

        // Vérifier si la requête n'est pas vide
        if (query !== '') {
            // Effectuer une requête à l'API Adresse pour obtenir des résultats d'autocomplétion
            var apiUrl = `https://api-adresse.data.gouv.fr/search/?q=${query}&autocomplete=1`;

            // Utiliser fetch pour faire la requête
            fetch(apiUrl)
                .then(response => response.json())
                .then(data => {
                    // Traiter les résultats de la réponse
                    var results = data.features;

                    // Afficher les résultats dans la liste déroulante
                    results.forEach(result => {
                        var listItem = document.createElement('li');
                        listItem.textContent = result.properties.label;
                        autocompleteResults.appendChild(listItem);

                        // Ajouter un gestionnaire d'événements pour remplir l'adresse dans le champ texte
                       // Ajouter un gestionnaire d'événements pour remplir l'adresse dans le champ texte
listItem.addEventListener('click', function() {
    // Retirer le code postal de l'adresse avant de l'afficher
    var addressWithoutPostalCode = result.properties.label.replace(/\s\d{5}$/, '');
    addressInput.value = addressWithoutPostalCode.trim();

    // Extraire le numéro de rue, le nom de rue et la ville de l'adresse
    var streetInfo = result.properties.street;
    var city = result.properties.city;

    // Construire l'adresse sans le code postal
    var newAddress = streetInfo + ', ' + city;

    // Remplir le champ du code postal avec le véritable code postal
    var postalCode = result.properties.postcode;
    document.getElementsByName('postal_code')[0].value = postalCode;

    // Remplacer la valeur de l'adresse par la nouvelle adresse
    addressInput.value = newAddress;

    // Effacer la liste des résultats
    autocompleteResults.innerHTML = '';
});

                    });
                })
                .catch(error => console.error('Error fetching data:', error));
        }
    });
});

</script>


</body>
</html>
{% endblock %}

website/templates/admin.html
{% extends "base.html" %}
{% block title %}Admin{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <h1>HIII ADMIN</h1>
  </div>
</div>
{% endblock %}

website/templates/admin_users.html
{% extends "base.html" %}
{% block title %}Admin{% endblock %}
{% block content %}
    <br>
    <style>
     .notes-column {
        padding-left: 20px; /* Ajustez cette valeur selon vos besoins */
    }
</style>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h1 class="text-center">Users</h1>
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                     <th class="notes-column">Notes</th>
                         <th>État</th>
                        <th>Action</th>

                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.email }}</td>
                       <td>
    {% if user.notes %}
        <ul>
            {% for note in user.notes %}
                <li>{{ note.data }}</li>
            {% endfor %}
        </ul>
    {% else %}
        Aucune note disponible
    {% endif %}
</td>
                    <td>
                          <form method="post" action="{{ url_for('views.toggle_user', id=user.id) }}" style="display: inline-block; margin-right: 5px;">
        <input type="hidden" name="id" value="{{ user.id }}">
        <button type="submit" class="btn {% if user.is_active %}btn-success{% else %}btn-danger{% endif %}">
            {% if user.is_active %}
                Actif
            {% else %}
                Désactif
            {% endif %}
        </button>
    </form>
                    </td>

                      <td>


    <form method="post" action="{{ url_for('views.delete_user', id=user.id) }}" style="display: inline-block;">
        <input type="hidden" name="id" value="{{ user.id }}">
        <button type="submit" class="btn btn-primary">Supprimer</button>
    </form>
</td>


                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />


    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
        aria-controls="navbar"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated  %}
          <a class="nav-item nav-link" id="profile" href="/profile" style="color: white">Home</a>
          <a class="nav-item nav-link" id="profile" href="/contacts" style="color: white">Contacts</a>
          <a class="nav-item nav-link" id="logout" href="/logout" style="color: white">Logout</a>

          {% elif is_admin %}
          <a class="nav-item nav-link" id="admin_users" href="/users" style="color: white">Users</a>
          <a class="nav-item nav-link" id="logout" href="/logout" style="color: white">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login" style="color: white">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up" style="color: white">Sign Up</a>
          {% endif %}
        </div>

        <!-- Ajout du menu déroulant avec le décalage vers la gauche -->
       <!-- Menu déroulant avec les trois tirets -->
        <!-- Menu déroulant avec les trois tirets -->
        <!-- Menu déroulant avec les trois tirets -->

      {% if user.is_authenticated %}
      <div class="navbar-nav ml-auto">
      <div class="nav-item dropdown">
      <i class="fa fa-bars" id="csvDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor: pointer; font-size: 1em; color: white;"></i>
      <!-- Ajout du logo "Dark Mode" -->


      <div class="dropdown-menu" aria-labelledby="csvDropdown" style="margin-left: -200px; margin-top: 24px">
 <a class="dropdown-item" href="{{ url_for('views.export_contacts_csv') }}">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 50 50" id="export" style="margin-right: 5px; vertical-align: -2px;">
        <path d="M49 15H30v2h17v30H3V17h17v-2H1v34h48z"></path>
        <path d="M26 33V5.414l4.293 4.293 1.414-1.414L25 1.586l-6.707 6.707 1.414 1.414L24 5.414V33z"></path>
    </svg>
    Exporter Fichier CSV
</a>


<a class="dropdown-item" href="#" data-toggle="modal" data-target="#importCsvModal">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 50 50" id="import" style="margin-left: 0px; vertical-align: -2px;">
        <path d="M49 15H30v2h17v30H3V17h17v-2H1v34h48z"></path>
        <path d="M24 1v27.586l-4.293-4.293-1.414 1.414L25 32.414l6.707-6.707-1.414-1.414L26 28.586V1z"></path>
    </svg>
    <span style="margin-left: 5px;">Importer Fichier CSV</span>
</a>



      </div>
      </div>
      </div>
      </div>
    {% endif %}
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <!-- Modal pour l'import CSV -->
    <div class="modal fade" id="importCsvModal" tabindex="-1" role="dialog" aria-labelledby="importCsvModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="importCsvModalLabel">Importer Fichier CSV</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <!-- Formulaire d'upload CSV -->
            <form id="importCsvForm" method="post" enctype="multipart/form-data" action="{{ url_for('views.import_csv') }}">
              <div class="form-group">
                <label for="csvFile">Choisir un fichier CSV</label>
                <input type="file" class="form-control-file" id="csvFile" name="file" accept=".csv" required>
              </div>
              <button type="submit" class="btn btn-primary">Importer</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    {% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
        fetch("/delete-note", {
          method: "POST",
          body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
          window.location.href = "/";
        });
      }
    </script>
    {% endblock %}
  </body>
</html>

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <style>
    body {
        background-color: white;
    }
    </style>
<div class="row justify-content-center">
  <div class="col-md-6">
    <form method="POST">
        <br>
      <div class="text-center">
        <h3>Login</h3>
      </div>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="text"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <div class="text-center">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
        <div class="mt-4 text-center">
            <a class="btn text-small" href="{{ url_for('auth.forgot') }}" style="color: grey;">Forgot Password ?</a>
            <a class="btn text-small" href="{{ url_for('auth.sign_up') }}" style="color: grey;">Doesn't have an account yet ?</a>
        </div>

    </form>
  </div>
</div>
{% endblock %}